name: Ferram Aerospace Research
description: Realistic aerodynamics
sources:
  - type: github
    repository: dkavolis/Ferram-Aerospace-Research
steps:
  - action: copy_folder
    glob: GameData
    to: GameData
  - action: copy_folder
    glob: Ships
    to: Ships
