name: Lint & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    if: always()
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - id: checkout
        name: Clone repository
        uses: actions/checkout@v2
      - id: lint
        name: Run linter
        run: make lint-docker

  test:
    if: always()
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - id: checkout
        name: Clone repository
        uses: actions/checkout@v2
      - id: test
        name: Run tests
        run: make tests
